# Generated by Django 2.1 on 2018-11-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_publicnetwork'),
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('recipients', models.ManyToManyField(to='account.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='labmessage',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='metabooking',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='notifier',
            name='user',
        ),
        migrations.DeleteModel(
            name='LabMessage',
        ),
        migrations.DeleteModel(
            name='MetaBooking',
        ),
        migrations.DeleteModel(
            name='Notifier',
        ),
    ]
