# Generated by Django 2.1 on 2019-01-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_auto_20181102_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_html',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
    ]
