# Generated by Django 2.1 on 2019-01-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_publicnetwork'),
        ('notifier', '0003_auto_20190123_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.AddField(
            model_name='notification',
            name='read_by',
            field=models.ManyToManyField(related_name='read_notifications', to='account.UserProfile'),
        ),
    ]
