# Generated by Django 2.1 on 2019-03-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0004_auto_20190124_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(related_name='notifications', to='account.UserProfile'),
        ),
    ]
