# Generated by Django 2.2 on 2020-12-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0006_emailed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('recipient', models.CharField(max_length=150)),
            ],
        ),
    ]
