# Generated by Django 2.2 on 2023-06-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0007_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipients',
        ),
        migrations.DeleteModel(
            name='Emailed',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
