---
##############################################################################
# Copyright (c) 2016 Max Breitenfeldt and others.
# Copyright (c) 2018 Parker Berberian, Sawyer Bergeron, and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
version: '3'
services:
    nginx:
        restart: always
        image: nginx:latest
        container_name: ng01
        ports:
            - "80:80"
        volumes:
            - ./config/nginx:/etc/nginx/conf.d
            - pharos-static:/static:ro
            - pharos-media:/media
        depends_on:
            - web

    web:
        image: opnfv/pharos-tools-laas-dashboard:latest
        restart: always
        container_name: dg01
        depends_on:
            - postgres
        links:
            - postgres
        env_file: config.env
        volumes:
            - pharos-static:/static
            - pharos-media:/media
        expose:
            - "8000"

    postgres:
        restart: always
        image: postgres:10
        container_name: ps01
        env_file: config.env
        volumes:
            - pharos-data:/var/lib/postgresql/data

    rabbitmq:
        restart: always
        image: rabbitmq
        container_name: rm01
        env_file: config.env
        ports:
            - "5672:5672"

    worker:
        image: opnfv/pharos-tools-laas-celery:latest
        restart: always
        env_file: config.env
        links:
            - postgres
            - rabbitmq
volumes:
    pharos-media:
    pharos-static:
    pharos-data:
        external: true
