version: "3"
services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
    links:
        - postgres
    env_file: config.env
    command: >
      sh -c "./manage.py test --noinput"
  postgres:
    restart: "always"
    image: postgres:16
    env_file: config.env
    volumes:
      - laas-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 10s
      start_period: 60s
      retries: 5
volumes:
    laas-data:
