# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-08 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_changeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='changeid',
            field=models.TextField(blank=True, default='initial', null=True),
        ),
    ]