# Generated by Django 2.1 on 2019-04-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20190124_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='idf',
            field=models.TextField(blank=True, default=''),
        ),
    ]
