# Generated by Django 2.1 on 2019-05-01 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0010_auto_20190430_1405'),
        ('booking', '0005_booking_idf'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='opnfv_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource_inventory.OPNFVConfig'),
        ),
    ]
