# Generated by Django 2.2 on 2020-02-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_opnfv_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='config_bundle',
        ),
    ]
