# Generated by Django 2.2 on 2021-09-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20201109_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
