# Generated by Django 2.2 on 2023-08-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_booking_aggregateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='aggregateId',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
