# Generated by Django 2.2 on 2024-06-14 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20230802_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringBookingNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('when', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('for_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
