# Generated by Django 2.2 on 2024-06-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_expiringbookingnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ext_count',
        ),
        migrations.AddField(
            model_name='booking',
            name='ext_days',
            field=models.IntegerField(default=42),
        ),
    ]
