# Generated by Django 5.0 on 2025-07-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20240620_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
