# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_addr',
            field=models.CharField(default='email@mail.com', max_length=300),
        ),
    ]
