# Generated by Django 2.1 on 2018-09-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='description',
            field=models.CharField(default='Lab description default', max_length=240),
            preserve_default=False,
        ),
    ]
