# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-10 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180110_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='id',
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
