# Generated by Django 2.2 on 2020-07-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_downtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='lab_info_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='project',
            field=models.CharField(default='LaaS', max_length=100),
        ),
    ]
