# Generated by Django 2.2 on 2021-03-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201109_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pulic_user',
            field=models.BooleanField(default=False),
        ),
    ]
