# Generated by Django 2.2 on 2021-03-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userprofile_pulic_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pulic_user',
            new_name='public_user',
        ),
    ]
