# Generated by Django 2.2 on 2023-06-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210324_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='vlan_manager',
        ),
        migrations.DeleteModel(
            name='PublicNetwork',
        ),
        migrations.DeleteModel(
            name='VlanManager',
        ),
    ]
