# Generated by Django 2.2 on 2023-07-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20230725_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='jira_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pgp_public_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ssh_public_key',
        ),
    ]
