# Generated by Django 5.0 on 2025-06-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20230727_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='about_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_home_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_logo_link',
            field=models.URLField(null=True),
        ),
    ]
