# Generated by Django 5.0 on 2025-06-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_lab_about_text_lab_lab_home_link_lab_lab_logo_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='contact_phone',
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_logo_link',
            field=models.URLField(help_text='Remote image resource, size will be constricted dynamically', null=True),
        ),
    ]
