# Generated by Django 5.0 on 2025-07-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_lab_contact_phone_alter_lab_lab_logo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='public_user',
            field=models.BooleanField(default=True),
        ),
    ]
