# Generated by Django 2.1 on 2018-09-14 14:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBundle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CpuProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cores', models.IntegerField()),
                ('architecture', models.CharField(choices=[('x86_64', 'x86_64'), ('aarch64', 'aarch64')], max_length=50)),
                ('cpus', models.IntegerField()),
                ('cflags', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiskProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('media_type', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('rotation', models.IntegerField(default=0)),
                ('interface', models.CharField(choices=[('sata', 'sata'), ('sas', 'sas'), ('ssd', 'ssd'), ('nvme', 'nvme'), ('scsi', 'scsi'), ('iscsi', 'iscsi')], default='sata', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GenericHost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GenericInterface',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='generic_interfaces', to='resource_inventory.GenericHost')),
            ],
        ),
        migrations.CreateModel(
            name='GenericResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Enter a valid hostname. Full domain name may be 1-253 characters, each hostname 1-63 characters (including suffixed dot), and valid characters for hostnames are A-Z, a-z, 0-9, hyphen (-), and underscore (_)', regex='(?=^.{1,253}$)(?=(^([A-Za-z0-9\\-\\_]{1,62}\\.)*[A-Za-z0-9\\-\\_]{1,63}$))')])),
            ],
        ),
        migrations.CreateModel(
            name='GenericResourceBundle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('xml', models.TextField()),
                ('description', models.CharField(default='', max_length=1000)),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Lab')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booked', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('labid', models.CharField(default='default_id', max_length=200)),
                ('working', models.BooleanField(default=True)),
                ('vendor', models.CharField(default='unknown', max_length=100)),
                ('model', models.CharField(default='unknown', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='HostConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bundle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostConfigurations', to='resource_inventory.ConfigBundle')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='resource_inventory.GenericHost')),
            ],
        ),
        migrations.CreateModel(
            name='HostProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host_type', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('labs', models.ManyToManyField(related_name='hostprofiles', to='account.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('public', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('from_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Lab')),
                ('host_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_inventory.HostProfile')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Installer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mac_address', models.CharField(max_length=17)),
                ('bus_address', models.CharField(max_length=50)),
                ('name', models.CharField(default='eth0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('speed', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('nic_type', models.CharField(choices=[('onboard', 'onboard'), ('pcie', 'pcie')], default='onboard', max_length=50)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='interfaceprofile', to='resource_inventory.HostProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vlan_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OPNFVConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opnfv_config', to='resource_inventory.ConfigBundle')),
                ('installer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_inventory.Installer')),
            ],
        ),
        migrations.CreateModel(
            name='OPNFVRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Opsys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sup_installers', models.ManyToManyField(blank=True, to='resource_inventory.Installer')),
            ],
        ),
        migrations.CreateModel(
            name='RamProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('channels', models.IntegerField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ramprofile', to='resource_inventory.HostProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceBundle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resource_inventory.GenericResourceBundle')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vlan_id', models.IntegerField()),
                ('tagged', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GenericPod',
            fields=[
                ('genericresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resource_inventory.GenericResource')),
            ],
            bases=('resource_inventory.genericresource',),
        ),
        migrations.AddField(
            model_name='opnfvconfig',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_inventory.Scenario'),
        ),
        migrations.AddField(
            model_name='interface',
            name='config',
            field=models.ManyToManyField(to='resource_inventory.Vlan'),
        ),
        migrations.AddField(
            model_name='interface',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='resource_inventory.Host'),
        ),
        migrations.AddField(
            model_name='installer',
            name='sup_scenarios',
            field=models.ManyToManyField(blank=True, to='resource_inventory.Scenario'),
        ),
        migrations.AddField(
            model_name='hostconfiguration',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resource_inventory.Image'),
        ),
        migrations.AddField(
            model_name='hostconfiguration',
            name='opnfvRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resource_inventory.OPNFVRole'),
        ),
        migrations.AddField(
            model_name='host',
            name='bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='resource_inventory.ResourceBundle'),
        ),
        migrations.AddField(
            model_name='host',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration', to='resource_inventory.HostConfiguration'),
        ),
        migrations.AddField(
            model_name='host',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Lab'),
        ),
        migrations.AddField(
            model_name='host',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_inventory.HostProfile'),
        ),
        migrations.AddField(
            model_name='host',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource_inventory.GenericHost'),
        ),
        migrations.AddField(
            model_name='genericresource',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='generic_resources', to='resource_inventory.GenericResourceBundle'),
        ),
        migrations.AddField(
            model_name='genericinterface',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resource_inventory.InterfaceProfile'),
        ),
        migrations.AddField(
            model_name='genericinterface',
            name='vlans',
            field=models.ManyToManyField(to='resource_inventory.Vlan'),
        ),
        migrations.AddField(
            model_name='generichost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resource_inventory.HostProfile'),
        ),
        migrations.AddField(
            model_name='generichost',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='generic_host', to='resource_inventory.GenericResource'),
        ),
        migrations.AddField(
            model_name='diskprofile',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='storageprofile', to='resource_inventory.HostProfile'),
        ),
        migrations.AddField(
            model_name='cpuprofile',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cpuprofile', to='resource_inventory.HostProfile'),
        ),
        migrations.AddField(
            model_name='configbundle',
            name='bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_inventory.GenericResourceBundle'),
        ),
        migrations.AddField(
            model_name='configbundle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genericpod',
            name='hosts',
            field=models.ManyToManyField(to='resource_inventory.GenericHost'),
        ),
        migrations.AddField(
            model_name='genericpod',
            name='networks',
            field=models.ManyToManyField(to='resource_inventory.Network'),
        ),
    ]
