# Generated by Django 2.1 on 2018-09-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostprofile',
            name='host_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
