# Generated by Django 2.1 on 2018-09-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0002_auto_20180919_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
