# Generated by Django 2.1 on 2018-10-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0003_vlan_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericpod',
            name='genericresource_ptr',
        ),
        migrations.RemoveField(
            model_name='genericpod',
            name='hosts',
        ),
        migrations.RemoveField(
            model_name='genericpod',
            name='networks',
        ),
        migrations.DeleteModel(
            name='GenericPod',
        ),
    ]
