# Generated by Django 2.1 on 2019-01-10 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0004_auto_20181017_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='os',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_inventory.Opsys'),
        ),
    ]
