# Generated by Django 2.1 on 2019-01-24 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resource_inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0005_image_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpuprofile',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpuprofile', to='resource_inventory.HostProfile'),
        ),
        migrations.AlterField(
            model_name='diskprofile',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storageprofile', to='resource_inventory.HostProfile'),
        ),
        migrations.AlterField(
            model_name='generichost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_inventory.HostProfile'),
        ),
        migrations.AlterField(
            model_name='generichost',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generic_host', to='resource_inventory.GenericResource'),
        ),
        migrations.AlterField(
            model_name='genericinterface',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_interfaces', to='resource_inventory.GenericHost'),
        ),
        migrations.AlterField(
            model_name='genericresource',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_resources', to='resource_inventory.GenericResourceBundle'),
        ),
        migrations.AlterField(
            model_name='genericresourcebundle',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Lab'),
        ),
        migrations.AlterField(
            model_name='genericresourcebundle',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hostconfiguration',
            name='opnfvRole',
            field=models.ForeignKey(on_delete=models.SET(resource_inventory.models.get_sentinal_opnfv_role), to='resource_inventory.OPNFVRole'),
        ),
        migrations.AlterField(
            model_name='interfaceprofile',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaceprofile', to='resource_inventory.HostProfile'),
        ),
        migrations.AlterField(
            model_name='ramprofile',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ramprofile', to='resource_inventory.HostProfile'),
        ),
        migrations.AlterField(
            model_name='resourcebundle',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource_inventory.GenericResourceBundle'),
        ),
    ]
