# Generated by Django 2.1 on 2019-03-06 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0006_auto_20190124_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=15)),
                ('mac_address', models.CharField(max_length=17)),
                ('password', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('management_type', models.CharField(default='ipmi', max_length=50)),
                ('versions', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='genericinterface',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_inventory.InterfaceProfile'),
        ),
    ]
