# Generated by Django 2.1 on 2019-03-06 16:42

from django.db import migrations, models
import resource_inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0007_auto_20190306_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='remote_management',
            field=models.ForeignKey(default=resource_inventory.models.get_default_remote_info, on_delete=models.SET(resource_inventory.models.get_default_remote_info), to='resource_inventory.RemoteInfo'),
        ),
    ]
