# Generated by Django 2.1 on 2019-03-15 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0008_host_remote_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_is_tagged', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NetworkRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='genericinterface',
            name='vlans',
        ),
        migrations.RemoveField(
            model_name='network',
            name='vlan_id',
        ),
        migrations.AddField(
            model_name='network',
            name='bundle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='resource_inventory.GenericResourceBundle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='is_public',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vlan',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='resource_inventory.Network'),
        ),
        migrations.AddField(
            model_name='networkrole',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_inventory.Network'),
        ),
        migrations.AddField(
            model_name='networkconnection',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_inventory.Network'),
        ),
        migrations.AddField(
            model_name='genericinterface',
            name='connections',
            field=models.ManyToManyField(to='resource_inventory.NetworkConnection'),
        ),
        migrations.AddField(
            model_name='opnfvconfig',
            name='networks',
            field=models.ManyToManyField(to='resource_inventory.NetworkRole'),
        ),
    ]
