# Generated by Django 2.2 on 2019-11-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0010_auto_20190430_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='configbundle',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configbundle',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genericresourcebundle',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genericresourcebundle',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
