# Generated by Django 2.2 on 2020-03-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0013_auto_20200218_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcetemplate',
            old_name='hidden',
            new_name='temporary',
        ),
    ]
