# Generated by Django 2.2 on 2020-04-13 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0014_auto_20200305_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetemplate',
            name='copy_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource_inventory.ResourceTemplate'),
        ),
    ]
