# Generated by Django 2.2 on 2020-11-09 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0015_resourcetemplate_copy_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalnetwork',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_inventory.ResourceBundle'),
        ),
        migrations.AddField(
            model_name='resourceconfiguration',
            name='name',
            field=models.CharField(default='<Hostname>', max_length=3000),
        ),
        migrations.AlterField(
            model_name='cpuprofile',
            name='cflags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='acts_as',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_inventory.InterfaceConfiguration'),
        ),
        migrations.AlterField(
            model_name='interfaceconfiguration',
            name='connections',
            field=models.ManyToManyField(blank=True, to='resource_inventory.NetworkConnection'),
        ),
        migrations.AlterField(
            model_name='resourcetemplate',
            name='copy_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource_inventory.ResourceTemplate'),
        ),
        migrations.AlterField(
            model_name='resourcetemplate',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='server',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource_inventory.ResourceBundle'),
        ),
        migrations.AlterField(
            model_name='server',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource_inventory.ResourceConfiguration'),
        ),
    ]
