# Generated by Django 2.2 on 2021-07-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0018_auto_20210630_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='lab_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='opsys',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='opsys',
            name='obsolete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resourceprofile',
            name='architecture',
            field=models.CharField(choices=[('x86_64', 'x86_64'), ('aarch64', 'aarch64')], max_length=50),
        ),
    ]
