# Generated by Django 2.2 on 2021-09-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0019_auto_20210701_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudInitFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
