# Generated by Django 2.2 on 2021-09-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0020_cloudinitfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceconfiguration',
            name='cloud_init_files',
            field=models.ManyToManyField(blank=True, to='resource_inventory.CloudInitFile'),
        ),
    ]
