# Generated by Django 2.2 on 2021-09-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0021_resourceconfiguration_cloud_init_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetemplate',
            name='private_vlan_pool',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resourcetemplate',
            name='public_vlan_pool',
            field=models.TextField(default=''),
        ),
    ]
