# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-10 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180110_1636'),
        ('dashboard', '0002_auto_20170505_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_resource_set', to='account.Lab'),
        ),
    ]
