# Generated by Django 2.1 on 2019-01-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_job_delta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessconfig',
            name='delta',
            field=models.TextField(default='{}'),
        ),
    ]
