# Generated by Django 2.1 on 2019-03-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_snapshotconfig_delta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opnfvapiconfig',
            name='installer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='opnfvapiconfig',
            name='scenario',
            field=models.CharField(max_length=300),
        ),
    ]
