# Generated by Django 2.1 on 2019-04-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190313_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='opnfvapiconfig',
            name='idf',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opnfvapiconfig',
            name='pdf',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
