# Generated by Django 2.1 on 2019-05-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190419_1414'),
        ('api', '0007_opnfvapiconfig_opnfv_config'),
    ]

    operations = [
    ]
