# Generated by Django 2.2 on 2019-12-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20190508_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconfig',
            name='delta_keys_list',
            field=models.CharField(default='[]', max_length=200),
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='state',
            field=models.IntegerField(default=200),
        ),
    ]
