# Generated by Django 2.2 on 2020-02-18 15:36

from django.db import migrations


def set_resource_id(apps, schema_editor):
    for cls in ["HostHardwareRelation", "HostNetworkRelation", "SnapshotConfig"]:
        model = apps.get_model('api', cls)
        for m in model.objects.all():
            m.resource_id = m.host.labid
            m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200218_1536'),
    ]

    operations = [
        migrations.RunPython(set_resource_id),
    ]
