# Generated by Django 2.2 on 2020-02-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_manual_20200218_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosthardwarerelation',
            name='host',
        ),
        migrations.RemoveField(
            model_name='hostnetworkrelation',
            name='host',
        ),
        migrations.RemoveField(
            model_name='snapshotconfig',
            name='host',
        ),
        migrations.RemoveField(
            model_name='opnfvapiconfig',
            name='roles',
        ),
    ]
