# Generated by Django 2.2 on 2020-11-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_manual_20200220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskconfig',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
