# Generated by Django 2.2 on 2021-06-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201109_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshotconfig',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
