# Generated by Django 2.2 on 2021-03-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_apilog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='ip_addr',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
