# Generated by Django 2.2 on 2021-03-22 18:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_apilog_ip_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='body',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
