# Generated by Django 2.2 on 2021-09-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20201109_1947'),
        ('resource_inventory', '0020_cloudinitfile'),
        ('api', '0018_cloudinitfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedCloudConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
                ('rconfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_inventory.ResourceConfiguration')),
            ],
        ),
        migrations.DeleteModel(
            name='CloudInitFile',
        ),
    ]
