# Generated by Django 2.2 on 2021-03-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210322_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='method',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='endpoint',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
