# Generated by Django 2.2 on 2021-04-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210322_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='method',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
