# Generated by Django 2.2 on 2021-11-02 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210907_1448'),
        ('api', '0021_auto_20210405_1943'),
    ]

    operations = [
    ]
