# Generated by Django 2.2 on 2023-06-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210405_1943'),
        ('api', '0019_auto_20210907_1448'),
    ]

    operations = [
    ]
