# Generated by Django 5.0 on 2025-06-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20230608_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='body',
            field=models.JSONField(null=True),
        ),
    ]
