# Generated by Django 2.2 on 2023-06-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20201109_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveVPNUser',
        ),
    ]
